services:
  redis:
    image: redis:7-alpine
    container_name: redis-demo
    ports:
      - "6380:6379" # host:container(inside docker)
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-ui
    ports:
      - "5540:5540"
    restart: unless-stopped

volumes:
  redis-data:

# docker run -d --name redis-demo -p 6379:6379 redis:7-alpine

# docker start redis-demo
# docker exec -it redis-demo redis-cli

# connect to redis workspace - http://localhost:5540/
